- src/main/java/uk/gov/caz/retrofit/amazonaws/RuntimeExceptionHandlerLambda.java
The new error message is "The upload was unsuccessful please try again. If the problem persists please contact us at TaxiandPHVCentralised.Database@defra.gov.uk"
> update timeout/outofmemory error message

- .drone.yml
Add production deploy step to drone file for Retrofit API.
> Feature/vccs 740/drone production

- src/main/java/uk/gov/caz/retrofit/amazonaws/StreamLambdaHandler.java
Fixes input stream mapping for thundra handlers on main Lambda function
> Fix for thundra handler in aws lambda stream inputs

- pom.xml
- src/main/java/uk/gov/caz/retrofit/amazonaws/StreamLambdaHandler.java
Remove code smell from InputStream manipulations in StreambLamdaHandler.
> NON-JIRA Remove code smell from InputStream manipulations in StreambLamdaHandler.

- src/main/java/uk/gov/caz/retrofit/amazonaws/StreamLambdaHandler.java
@phan-anh-tuan - FYI on the below changes,
> Fix thundra handler

- pom.xml
- src/it/java/uk/gov/caz/retrofit/RegisterTestIT.java
- src/main/java/uk/gov/caz/retrofit/amazonaws/RetrofitRegisterCsvFromS3Lambda.java
- src/main/java/uk/gov/caz/retrofit/amazonaws/StreamLambdaHandler.java
- src/main/java/uk/gov/caz/retrofit/dto/LambdaContainerStats.java
- src/main/java/uk/gov/caz/retrofit/repository/RetrofittedVehicleDtoCsvRepository.java
- src/main/java/uk/gov/caz/retrofit/service/AbstractRegisterCommand.java
- src/main/java/uk/gov/caz/retrofit/service/RegisterFromCsvCommand.java
- src/test/java/uk/gov/caz/retrofit/repository/RetrofittedVehicleDtoCsvRepositoryTest.java
- src/test/java/uk/gov/caz/retrofit/service/RegisterFromCsvCommandTest.java
> Retrofit API refresh

- .drone.yml
> [CI SKIP] Update drone file for sit subscriptions

- pom.xml
- src/it/java/uk/gov/caz/retrofit/RegisterTestIT.java
Add fixed security headers to all responses from API endpoints.
> TPDPB-5 - Add fixed security headers to all responses from API endpoints.

- .drone.yml
- ci-cd-resources/subscribe_to_alert_topics.py
Updates security headers in the API layer
> Update security headers

- .drone.yml
Add nightly steps to Retrofit API
> Add nightly steps

- .drone.yml
- ci-cd-resources/subscribe_to_alert_topics.py
- pom.xml
- src/it/java/uk/gov/caz/retrofit/RegisterTestIT.java
- src/main/java/uk/gov/caz/retrofit/amazonaws/RetrofitRegisterCsvFromS3Lambda.java
- src/main/java/uk/gov/caz/retrofit/amazonaws/StreamLambdaHandler.java
- src/main/java/uk/gov/caz/retrofit/dto/LambdaContainerStats.java
- src/main/java/uk/gov/caz/retrofit/repository/RetrofittedVehicleDtoCsvRepository.java
- src/main/java/uk/gov/caz/retrofit/service/AbstractRegisterCommand.java
- src/main/java/uk/gov/caz/retrofit/service/RegisterFromCsvCommand.java
- src/main/resources/logback-spring.xml
- src/test/java/uk/gov/caz/retrofit/repository/RetrofittedVehicleDtoCsvRepositoryTest.java
- src/test/java/uk/gov/caz/retrofit/service/RegisterFromCsvCommandTest.java
Promote release v1.0.0 to Production
> Promote release v1.0.0 to Production

- .drone.yml
Add ST pipeline steps to retrofit API
> Add ST pipeline steps

- src/main/java/uk/gov/caz/retrofit/service/CsvObjectMapper.java
[Link to CAZSM-12 JIRA Card](https://eaflood.atlassian.net/browse/CAZSM-12)
> [CAZSM-12] Removal of VRNs from application logs

- .drone.yml
This is a temporary change that should be overwritten by the drone pipeline in develop when the refactored python script in develop is promoted to UAT.
> Correct python script invocation for uat environment

- .drone.yml
Fix db schema migrations by setting Alpine to fixed version pre-3.12
> Fix db schema migrations

- .drone2.yml
> updated alpine image version

- .drone2.yml
Updated drone changes for sit environment
> Updated drone changes for sit environment

- .drone2.yml
> Promote SIT step fixes

- .drone.yml
- Makefile
- src/it/java/uk/gov/caz/retrofit/RegisterTestIT.java
- src/it/resources/data/csv/second-uploader-mixed-business-parse-errors.csv
- src/main/java/uk/gov/caz/retrofit/amazonaws/StreamLambdaHandler.java
- src/main/java/uk/gov/caz/retrofit/service/AbstractRegisterCommand.java
- src/main/java/uk/gov/caz/retrofit/service/RetrofittedVehicleDtoToModelConverter.java
- src/test/java/uk/gov/caz/retrofit/service/RegisterFromCsvCommandTest.java
- src/test/java/uk/gov/caz/retrofit/service/RetrofittedVehicleDtoToModelConverterTest.java
Update new AWS Environment baseline
> Update new AWS Environment baseline

- .drone2.yml
Correct preprod pointer in new prod plan step
> Correct preprod pointer in new prod plan step

- src/it/java/uk/gov/caz/retrofit/RegisterTestIT.java
- src/it/resources/data/csv/second-uploader-mixed-business-parse-errors.csv
- src/main/java/uk/gov/caz/retrofit/dto/validation/VrnValidator.java
- src/test/java/uk/gov/caz/retrofit/dto/validation/VrnValidatorTest.java
As in the title 
VRN starting from zeroes should generate an error
https://eaflood.atlassian.net/browse/CAZB-1664
> CAZB-1664 VRN with leading zeroes generate error

- .drone.yml
https://eaflood.atlassian.net/browse/CAZB-1979
> CAZB-1979 Call to `/v1/load-test-data` in drone build step

- .drone.yml
- src/main/java/uk/gov/caz/retrofit/controller/TestFixturesController.java
- src/main/java/uk/gov/caz/retrofit/service/TestFixturesLoader.java
Update ST with RC 1.4.0 in the new AWS environment
> Update ST with RC 1.4.0 in the new AWS environment

- .drone2.yml
> Update ST retrofit API

- .drone.yml
- .drone2.yml
- Makefile
- ci-cd-resources/subscribe_to_alert_topic_iac_restructure.py
- ci-cd-resources/subscribe_to_alert_topics.py
- pom.xml
- src/it/java/uk/gov/caz/retrofit/RegisterTestIT.java
- src/it/resources/data/csv/second-uploader-mixed-business-parse-errors.csv
- src/main/java/uk/gov/caz/retrofit/amazonaws/StreamLambdaHandler.java
- src/main/java/uk/gov/caz/retrofit/service/AbstractRegisterCommand.java
- src/main/java/uk/gov/caz/retrofit/service/RetrofittedVehicleDtoToModelConverter.java
- src/test/java/uk/gov/caz/retrofit/service/RegisterFromCsvCommandTest.java
- src/test/java/uk/gov/caz/retrofit/service/RetrofittedVehicleDtoToModelConverterTest.java
Cutover SIT domain for Release v1.3.0
> Cutover SIT domain for Release v1.3.0

- pom.xml
- src/main/java/uk/gov/caz/retrofit/repository/RetrofittedVehiclePostgresRepository.java
- src/main/java/uk/gov/caz/retrofit/service/RegisterService.java
- src/test/java/uk/gov/caz/retrofit/repository/RetrofittedVehiclePostgresRepositoryTest.java
Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-2986
> [CAZB-2986] Delete vehicles in batches

- src/main/java/uk/gov/caz/retrofit/amazonaws/RuntimeExceptionHandlerLambda.java
Update error messaging copy observed in test findings
> [CAZB-2896] Update error mesage for lambda timeouts

- src/main/resources/application.yml
https://eaflood.atlassian.net/browse/CAZB-3144
> [CAZB-3144] set correlation id logger to info level

- src/main/resources/application.yml
Remove Spring banner from logs
> [CAZB-3516] Remove Spring banner from logs

- pom.xml
- src/main/resources/application.yml
Promote Retrofit v1.6.0 to Staging
> Promote Retrofit v1.6.0 to Staging

- src/main/resources/application.yml
Promote Retrofit v1.7.0 to Pre-Production
> Promote Retrofit v1.7.0 to Pre-Production

- pom.xml
- src/main/resources/application.yml
Promote Retro v1.7.0 to Production
> Promote Retro v1.7.0 to Production

- pom.xml
Reverts InformedSolutions/JAQU-CAZ-Retrofit-API#156
> Revert "Bump springfox-bean-validators from 2.9.2 to 3.0.0"

- pom.xml
- src/main/java/uk/gov/caz/retrofit/amazonaws/StreamLambdaHandler.java
- src/test/java/uk/gov/caz/retrofit/repository/RegisterJobRepositoryTest.java
Update retrofit stream lambda handler
> [CAZB-3963] Update retrofit stream lambda handler

- pom.xml
Log request ids in application logs by updating pom.xml common libs version.
> [CAZB-4571] Log request ids in application logs

- pom.xml
* Link to JIRA Card: https://eaflood.atlassian.net/browse/CAZB-4972
> [CAZB-4972] Updated Spring Boot to 2.4.6

- Makefile
- pom.xml
- src/it/java/uk/gov/caz/retrofit/controller/HistoricalInfoControllerDroneOnlyIT.java
- src/it/java/uk/gov/caz/retrofit/controller/HistoricalInfoControllerIT.java
- src/main/java/uk/gov/caz/retrofit/dto/validation/VrnValidator.java
- src/test/java/uk/gov/caz/retrofit/dto/validation/VrnValidatorTest.java
Retrofit API v1.12.0 from SIT to PP
> [CAZB-4249] DVLA compliant regex for plates (#213)

- .drone2.yml
Add SIT2 pipeline steps to Release v1.13.0
> Add SIT2 pipeline steps to Release v1.13.0
